# Generated by Django 4.1.8 on 2023-04-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='', max_length=30, unique=True)),
                ('url_meteo', models.URLField(default='')),
                ('description', models.TextField(default='')),
                ('direction', models.CharField(default='', max_length=3)),
                ('latitude_takes_off', models.CharField(default='', max_length=10)),
                ('longitude_takes_off', models.CharField(default='', max_length=10)),
                ('latitude_landing', models.CharField(default='', max_length=10)),
                ('longitude_landing', models.CharField(default='', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
