# Generated by Django 4.1.8 on 2023-04-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='owner',
            new_name='user',
        ),
    ]
