# Generated by Django 4.1.8 on 2023-04-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0003_rename_owner_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude_landing',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude_takes_off',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude_landing',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude_takes_off',
        ),
        migrations.RemoveField(
            model_name='place',
            name='url_meteo',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
    ]
