# Generated by Django 4.1.8 on 2023-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0006_remove_place_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='url_meteo',
            field=models.URLField(default=''),
        ),
    ]
