# Generated by Django 4.1.8 on 2023-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0007_place_url_meteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='direction',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude_landing',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude_takes_off',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude_landing',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude_takes_off',
            field=models.CharField(default='', max_length=10),
        ),
    ]
