# Generated by Django 4.1.8 on 2023-04-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0009_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='owner',
        ),
    ]
