# Generated by Django 4.1.8 on 2023-04-29 05:36

from django.db import migrations, models
import paragliding_place.api_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0011_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.CharField(max_length=50, verbose_name=paragliding_place.api_auth.models.AppUser),
        ),
    ]
