# Generated by Django 4.1.8 on 2023-05-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0018_alter_place_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='direction',
            field=models.JSONField(),
        ),
    ]
