# Generated by Django 4.1.8 on 2023-06-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0019_alter_place_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description',
            new_name='description_landing',
        ),
        migrations.AddField(
            model_name='place',
            name='description_launch',
            field=models.TextField(default=''),
        ),
    ]
