# Generated by Django 4.1.8 on 2023-06-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0020_rename_description_place_description_landing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='url_meteo',
        ),
    ]
