# Generated by Django 4.1.8 on 2023-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0021_remove_place_url_meteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
