# Generated by Django 4.1.8 on 2023-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0022_comments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
