# Generated by Django 4.1.8 on 2023-06-21 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_place', '0023_alter_comments_owner_alter_comments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='place_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_place.place'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
