# Generated by Django 4.1.8 on 2023-06-21 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_place', '0024_alter_comments_place_comment_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='place_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api_place.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
