# Generated by Django 4.1.8 on 2023-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0025_alter_comments_place_comment_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='place_comment',
            field=models.IntegerField(default='', max_length=500),
        ),
    ]
