# Generated by Django 4.1.8 on 2023-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_place', '0026_alter_comments_place_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='place_comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
